Added volumeMounts and resource values
kubealex/k8s-mediaserver-operator pull request #14
Opened 2021-11-29 05:10 UTC by InputObject2

I added a section under storage to specify where the physical path of every tool should be. I'm keeping the same defaults but allowing the paths to be changed.

```yaml
general:
  storage:
    media:
      tv: media/tv 
      movies: media/movies
      downloads: downloads/transmission
      sabnzbd: downloads/sabnzbd
      config: config
```

I'm also adding a `resources` block to every tool, so you can define limits and requests for each pod, with no resources defined at the start in keeping with other projects.

2021-12-10 14:23 UTC, kubealex commented
Hi, sorry for taking longer in reviewing this one, but last week has been a bit busy. I will take a look at it during the weekend ;)

2021-12-12 11:29 UTC, kubealex commented
I find the 'resources' field perfect, but I am struggling to find a proper reason to make folders configurable, do you have any use case that can be used as a sample? @InputObject2

2021-12-13 00:56 UTC, stevelipinski commented
Configurable folders are useful for aligning with an external Plex server connected to a NAS (e.g., running k8s-mediaserver with plex.enabled=false), and/or using an already-configured volume that has a media directory-structure already established.  In such cases, you may need to alter the paths to where Plex is configured to find the media on the shared volume.

2021-12-15 02:10 UTC, InputObject2 commented
As @stevelipinski said, this is exactly my use case: I have an existing plex server with a directory structure, I'm trying to migrate to having plex exclusively in Kubernetes. I'd rather not have to move several TB's of media  over into another folder when I could reuse the existing one.

For example, I'm using as a pv:

```/nfs-server.local/media/```

Where my movies and shows are at:

```/nfs-server.local/media/movies```
```/nfs-server.local/media/shows```


But with the current state of the chart, if I pass /media as a pv, it'll create other folders on top:

```/nfs-server.local/media/media/movies```
```/nfs-server.local/media/media/shows```

With the changes I'm proposing, I could just make the paths `/movies` and `/shows` and get the structure I was aiming for in the beginning.

2021-12-19 11:58 UTC, kubealex requested changes
I'd move paths to single components and edit references accordingly as it is not a 'general' modifcation (especially for transmission and torznab).
Don't forget to edit the README to include new variables!

2021-12-30 14:22 UTC, kenmccann commented
Agree completely with this PR.  This is a fantastic project that was the kick I needed to scrap the old patchwork of YAMLs I was using to run these same services on an old Kubernetes cluster.  The one major drawback for me was the inability to leverage an existing data store.

For example, ask Sonarr to move processed shows/episodes to a pre-existing NFS storage array, one which has much more storage than I can (or am willing to) provide to k8s persistent volume.

2021-12-30 17:22 UTC, kubealex commented
I did some modifications to naming and added a condition for choosing /downloads path mounting in sonarr/radarr based on which is enabled if transmission or torznab to avoid conflicts.

2021-12-30 17:26 UTC, merged

2021-12-30 18:40 UTC, kubealex commented
Added this to master and release v0.6! Thank you @InputObject2 and @kenmccann for the inputs and contributions!

2021-12-30 18:45 UTC, kenmccann commented
I noticed that you removed the ability to run both transmission and sabnzbd at the same time.  I do :)

2021-12-31 16:51 UTC, kubealex commented
My new PR solves the issue, now the root /downloads is mounted in radarr and sonarr, giving it access to the subfolders transmission/* and sabnzbd/* and enabling you to use both of them!  
Please it would be great if in the next days you could give me some feedback over the sabnzbd part, as I am not able to test it :) @kenmccann